-- Run this in your Supabase SQL Editor to create the todos table

CREATE TABLE IF NOT EXISTS todos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  completed BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (optional, recommended for production)
ALTER TABLE todos ENABLE ROW LEVEL SECURITY;

-- Allow public access for demo purposes
-- In production, implement proper user authentication
CREATE POLICY "Enable all access for todos" ON todos
  FOR ALL
  USING (true)
  WITH CHECK (true);
